language: android
android:
  components:
    - platform-tools
    - build-tools-23.0.1
    - android-23

    # Additional components
    - extra-google-google_play_services
    - extra-google-m2repository
    - extra-android-m2repository
    - addon-google_apis-google-19

    # if you need to run emulator(s) during your tests
    - sys-img-armeabi-v7a-android-19
    - sys-img-x86-android-17
before_script: cd Helloworld
script:
   - ./gradlew test
   - ./gradlew build connectedCheck
